### ISSUE TITLE
Issue with Routes: Extra Slash Appears When Removing Action Names

### ISSUE THREAD

**Issue by YosstinCode** [igorbenav/fastcrud#135]
**Is your feature request related to a problem? Please describe.**

I'm not sure if it's a problem, but what happens is that I want to remove the route names that indicate the action, so this:  

![image](https://github.com/user-attachments/assets/5e1e684a-63e4-4c11-8277-35a7e317c1a2)
I wanna to pass to something like this:

![image](https://github.com/user-attachments/assets/e9200463-5d58-4e3c-99cb-83fc16f6477b)
but when I try to do it, this happens:

![image](https://github.com/user-attachments/assets/3299a3b4-dadc-44d7-9769-49babb1b7aae)

**Describe the solution you'd like**

Since this breaks a bit with what I wanted, and it seems strange to me that when I put an empty string in the endpoint_names argument, an extra slash appears at the end. According to me, one of two things should happen: the first is that it remains as it is by default, or the second, which is what I want, is to remove the extra slash.

![image](https://github.com/user-attachments/assets/e7f8f8b4-0169-45d2-a954-205520971d1b)

**Describe alternatives you've considered**

Regarding solutions, the truth is that it would be to adapt that part. I was considering making a pull request, but it requires first reading the code and, honestly, I'm not sure if I'm at that point yet, but I will try and leave an update soon in any case wheter or not to make a pull request

**Comment by igorbenav** [comment]
This was fixed in #105. It will be in the next release, probably it will be released by the weekend

**Comment by igorbenav** [comment]
Fixed in latest release

**Comment by natehouk** [comment]
This issue remains in version 0.14.0 and the mainline code. Double slashes still appear when an empty string is passed as the endpoint name.

If `endpoint_names` is not set, the double slash problem is resolved, and the default paths are correct. However, when an empty string is explicitly passed, the double slashes reappear in the paths, which should not happen.
